apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: your-dockerhub-username/backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_HOST
          value: db
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          value: postgres
        - name: DATABASE_USER
          value: postgres
        - name: DATABASE_PASSWORD
          value: postgres
